export const productDataList = [
  {
    productName: "Local Red Brick - 8-10 x 3.8 x 2.9",
    price: {
      mrp: 14,
      cost: 12,
      discountPercent: 14,
    },
    subcategory: 'Blocks',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/v/i/vijayawadaredbrick_2.jpg",
    category: 'Bricks',
    description: "We supply the best quality red clay bricks at the most affordable prices on the market and get free shipping. Check red clay bricks price list today in Hyderabad. We supply all Vijayawada bricks, Karimnagar bricks, Maharashtra bricks, Rajahmundry bricks, Karnataka bricks, Local bricks etc.",
    tagline: 'New Arrival',
    quantity: 1000,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Sugna TMT Fe-550 Grade - 16mm",
    price: {
      mrp:  92115.00,
      cost: 62155.00 ,
      discountPercent: 32,
    },
    subcategory: 'Steel',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/s/u/sugna_tmt_image_3.jpg",
    category: 'Steel Bars',
    description: "Fe-550 Grade 16mm Sugna TMT Bars, Prices Displayed are per Ton",
    tagline: 'Prices Displayed are per Ton, Transpotation & Unloading Extra as applicable Transpotation and Hamali Extra',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Birla.A1 StrongCrete",
    price: {
      mrp: 470.00,
      cost: 340.00,
      discountPercent: 27,
    },
    subcategory: 'Cement',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/c/e/ceba1cre0002_2.png",
    category: 'Cements',
    description: "Benefits of Birla.A1 Strongcrete Higher Eartly Strength Faster Setting time Denser concrete Crack resistant Corrosion inhibitor PST (Pressure Sustaining Technology) Birla.A1 Stongcrete, specially designed cement that builds stronger concrete structures in a lesser duration of time. Load bearing concrete structures of your dream home like the foundation, columns, beams and slabs are the most critical elements which is why they require special cement that can sustain very high pressure and withstand harsh climatic conditions. Birla.A1 StrongCrete comes in specially made LPP (laminated polypropyiene) bags which are tamper-proof, ensuring that there is no wastage of cement during its transportation and handling at the construction site. The moisture-proof property of these bags keeps the cement fresh.NOTE - Avoid using hooks while handling the bags on site.",
    tagline: 'Bira A1 StrongCrete Cement Price',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Sand (Refined)",
    price: {
      mrp: 3500.00,
      cost: 1830.00,
      discountPercent: 47,
    },
    subcategory: 'Sand',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/p/i/pit-sand.jpg",
    category: 'Sands',
    description: "Usage/Application Construction Material Sand Refined Color Brown Packaging Type Lorry Brand Generic Sand Type Refined State Telangana Country of Origin Made in India Product Description Refined River Sand at Best Price Online from Verified Sand Suppliers in Hyderabad. Also, buy other types of Aggregates & Sand with Free Delivery in Hyderabad",
    tagline: 'Limited Stock',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Robo Sand",
    price: {
      mrp: 1050.00,
      cost: 600.00,
      discountPercent: 42,
    },
    subcategory: 'Sand',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/r/b/rb.jpg",
    category: 'Sands',
    description: "Robo sand is sand manufactured in the stone quarries. It is a substitute for the river sand used in construction. ... Following a meeting of owners of stone crushing firms, the Minister said the Government is keen to encourage use of Robo sand as a substitute to natural sand.",
    tagline: 'Limited Stock',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Gray Construction Aggregates ., Packaging Type: Loose",
    price: {
      mrp: 500,
      cost: 450,
      discountPercent: 20,
    },
    subcategory: 'Stone',
    productImage: "https://5.imimg.com/data5/SELLER/Default/2023/6/316797307/VY/GJ/TL/189379796/construction-agrigate-500x500.png",
    category: 'Aggregates',
    description: "Use for Road and building materials Quality of material is very high and trustable We also deal with cement , sand , aggregate and white cement.",
    tagline: 'Limited Stock',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Black Gitti Construction Aggregates",
    price: {
      mrp: 1500,
      cost: 1400,
      discountPercent: 40,
    },
    subcategory: 'Stone',
    productImage: 'https://5.imimg.com/data5/SELLER/Default/2024/5/415207654/CP/SG/WU/138006909/gitti-construction-aggregates-500x500.png',
    category: 'Aggregates',
    description: "40 mm Kabrai Aggricate 50 Rupye Feet Established in the year 2013 at Lucknow, India. We “A P Enterprises a Sole",
    tagline: 'Stock Avaliable',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: '12mm Construction Aggregate, Packaging Size: 1 To 4 Ton',
    price: {
      mrp: 1800,
      cost: 1500,
      discountPercent: 40,
    },
    subcategory: 'Stone',
    productImage: 'https://5.imimg.com/data5/BG/JR/MY-9927785/12mm-construction-aggregate-500x500.jpg',
    category: 'Aggregates',
    description: 'Relying on our expertise in this domain, we are into offering 12mm Construction Aggregate.',
    tagline: 'Stock Avaliable',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: '20mm Crushed Stone',
    price: {
      mrp: 1000,
      cost: 950,
      discountPercent: 20,
    },
    subcategory: 'Stone',
    productImage: 'https://5.imimg.com/data5/SELLER/Default/2023/6/313159411/TS/HM/OH/22886627/20mm-crushed-stone-500x500.jpg',
    category: 'Aggregates',
    description: '20mm Crushed Stone Locally known as 20mm or 3/4 inches. These stones are usually between greater than 16mm and less than 22mm. It will make your construction work stronger and more durable. These stone suit the heavier duty operations and is largely used by civil contractors.',
    tagline: 'Limited Stock',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: 'Gray M Sand, Packaging Type: Truck, Grade: Vsi',
    price: {
      mrp: 3990,
      cost: 3800,
      discountPercent: 50,
    },
    subcategory: 'Sand',
    productImage: 'https://5.imimg.com/data5/TY/TK/BH/ANDROID-60373405/product-jpeg.jpg',
    category: 'Sands',
    description: 'Manufactured sand is artificial sand obtained from crushing hard stones into small sand-sized angular-shaped particles, washed and finely graded to be used as construction aggregate. It is an alternative to River Sand used for construction purposes.',
    tagline: 'Grab Now!',
    quantity: 1000,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Construction Quality Grey P Sand, For Civil Contstruction Work, Grade Standard",
    price: {
      mrp: 1300,
      cost: 1200,
      discountPercent: 25,
    },
    subcategory: 'Sand',
    productImage: "https://5.imimg.com/data5/SELLER/Default/2022/6/HW/YN/TZ/53418017/p-sand.jpg",
    category: 'Sands',
    description: 'The full form of P sand is Plastering Manufactured Sand which is also known as crushed sand or manufactured fine aggregate. This type of sand is used in construction greatly. They are a very fine grade of sand used mainly for plastering and creating renders. They give a very smooth finish to the plasters.',
    tagline: 'New Arrival',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Cylindrical Hot Rolled Stainless Steel Rod, 6 meter, Material Grade: SS316",
    price: {
      mrp: 290,
      cost: 190,
      discountPercent: 50,
    },
    subcategory: 'Steel',
    productImage: "https://5.imimg.com/data5/MZ/QX/ZG/SELLER-84990683/ss-pipe-500x500.jpg",
    category: 'Steel Bars',
    description: 'A cylindrical hot rolled stainless steel rod, 6 meters in length and made from material grade SS316, offers excellent corrosion resistance, particularly against chlorides and acidic environments. This robust and durable rod is ideal for use in marine, chemical, and pharmaceutical applications due to its high strength, weldability, and resistance to pitting and crevice corrosion. The hot rolling process ensures a smooth finish and uniform mechanical properties throughout the rod.',
    tagline: 'New Arrival',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Tata Steel Rod, For Construction",
    price: {
      mrp: 150,
      cost: 120,
      discountPercent: 10,
    },
    subcategory: 'Steel',
    productImage: "https://5.imimg.com/data5/SELLER/Default/2024/4/407492011/DE/VU/ZK/30880166/tata-steel-rod-250x250.jpeg",
    category: 'Steel Bars',
    description: 'Tata Steel Rods for construction are high-quality, durable reinforcement bars designed to provide superior strength and stability to concrete structures. These rods are known for their excellent tensile strength, ductility, and resistance to seismic forces, making them ideal for various construction projects.',
    tagline: 'Stock Available',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: 'Hot Rolled Tata Steel Rod, For Construction, 18 meter',
    price: {
      mrp: 100,
      cost: 85,
      discountPercent: 20,
    },
    subcategory: 'Steel',
    productImage: 'https://5.imimg.com/data5/SELLER/Default/2021/8/QN/MO/PM/90830723/tata-steel-rod-500x500.jpg',
    category: 'Steel Bars',
    description: 'The 18-meter hot rolled Tata Steel rod is specifically designed for construction applications, offering exceptional strength and durability. It provides reliable reinforcement for concrete structures, ensuring stability and resistance to bending and seismic forces.',
    tagline: 'Deal of the day',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: 'Ultratech Super Cement',
    price: {
      mrp: 380.00,
      cost: 340.00,
      discountPercent: 10,
    },
    subcategory: 'Cement',
    productImage: 'https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/u/l/ultratech_cement.jpg',
    category: 'Cements',
    description: 'Prices Displayed are per 50Kg Bag. Price of ultratech cement changes on daily basis and we have the todays updated price of ultratech cement. Prices are valid only in Hyderabad, India. Features: • Quality tested • Highly adhesive • Balanced composition • Smoother finish and high resistance to seepage • Higher resistance to ‘cracking’ due to low heat-of-hydration UltraTech cement is the ultimate 360° building materials destination, providing an array of products ranging from grey cement to white cement, from building products to building solutions and an assortment of ready mix concretes catering to the varied needs and applications. Ordinary Portland cement is the most commonly used cement for a wide range of applications. These applications cover ordinary, standard, high strength concretes, masonry and plastering works, precast concrete products for e.g., blocks, pipes etc., and specialized works such as precast and prestressed concrete. Ultratech Super Cement Price in Hyderabad',
    tagline: 'Deal of the Day',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Bharathi Ultra Fast Cement",
    price: {
      mrp: 480.00,
      cost: 330.00,
      discountPercent: 31,
    },
    subcategory: 'Cement',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/b/h/bharathi_7.jpg",
    category: 'Cements',
    description: "Bharathi OPC 53-Grade Cement is specially blended with good quality control monitoring systems, high quality cement engineered for use in all structural, building and particularly useful in marine and hydraulic construction. Benefits: Longest working hours with concrete, high fineness, least rate of cracking, and high workability Usage: Domestic, preferred in concreting & plastering wor",
    tagline: 'New Arrival',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Birla.A1 PPC Cement",
    price: {
      mrp: 480,
      cost: 367,
      discountPercent: 23,
    },
    subcategory: 'Cement',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/b/i/birla_a1_ppc_cement_2.jpg",
    category: 'Cements',
    description: "Birla.A1 PPC Cement. PPC Cement is used for brickworks, plastering and all other not structural cement works, it has more flyash content than OPC. PPC cement is used where Extra Durability is required and is preferred in mass construction. It usally cost less than OPC. Prices Displayed are per 50Kg Bag. Price of Birla.A1 cement changes on daily basis and we have the today's updated price of Birla.A1 cement. Prices are valid only in Hyderabad, India. Free shipping for orders above 50 Bags.",
    tagline: 'New Arrival',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Ultratech's AAC Blocks - 6",
    price: {
      mrp: 95.00,
      cost: 66.00,
      discountPercent: 30,
    },
    subcategory: 'Blocks',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/a/a/aac_block_1_2.jpg",
    category: 'Bricks',
    description: "Autoclaved Aerated Blocks is an higher quality product.it is manufactured with the latest automated technology providing international quality at an affordable price. Our plant production capacity is 500 CBM per day,we are dedicated and committed to meet the growing demand of AAC Blocks in the market. AAC is alight weight blocks suitable for construction of all types of residential and commercial buildings.our products are Eco-friendly and energy conserving materials.",
    tagline: 'Avaliable',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
  {
    productName: "Karimnagar Red Brick",
    price: {
      mrp: 13.00,
      cost: 11.20,
      discountPercent: 13,
    },
    subcategory: 'Blocks',
    productImage: "https://cdn-media.buildersmart.in/media/catalog/product/cache/1/image/200x200/9df78eab33525d08d6e5fb8d27136e95/k/a/karimnagar_red-brick.jpg",
    category: 'Bricks',
    description: "Karimnagar clay bricks are very strong in quality and cost-effective. Karimnagar Clay Bricks are manufactured using the highest quality raw materials and cutting-edge techniques under the guidance of qualified professionals, in accordance with industry standards. We are here to deliver the these quality red bricks at the most affordable prices on the market with free of delivery and unloading. Check today’s Karimnagar bricks price. We also supply AAC blocks, and Solid concrete blocks.",
    tagline: 'Avaliable',
    quantity: 100,
    seller: "665426181f34b6af49b1409b",
  },
];

export const bannerData = [
  { _id: 1, url: 'https://cdn-media.buildersmart.in/media/bannerslider/bannerslider/cement_tmt_price_drop...jpg' },
  //{ _id: 1, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/8464e4d9a75b909a.jpg?q=50' },
  
  { _id: 2, url: 'https://cdn-media.buildersmart.in/media/bannerslider/bannerslider/Check_Price......jpg' },
  // { _id: 2, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/a5320d3f852657e8.jpg?q=50' },

  { _id: 3, url: 'https://cdn-media.buildersmart.in/media/bannerslider/bannerslider/Discover_Guranteed_web...jpg' },
  // { _id: 3, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/5df65ad101e18dbf.jpg?q=50' },

  { _id: 4, url: 'https://cdn-media.buildersmart.in/media/bannerslider/bannerslider/Buy_Online_Save_Money_..jpg' },
  // { _id: 4, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/8a89ee09acc1a9e5.jpg?q=50' },

  // { _id: 5, url: 'https://rukminim1.flixcart.com/flap/3376/560/image/ed12b7707a04473c.jpg?q=50' },
]